### ISSUE TITLE
Feature request: Support the new Stream Deck +

### ISSUE THREAD

**Issue by jonjonsson** [CZDanol/streamdeck-discordmixer#13]
This would be perfect for the new stream deck knobs. Cycling through the users by clicking on the knob. Oh my! 

https://www.elgato.com/en/stream-deck-plus

**Comment by CZDanol** [comment]
I don't have the unit, and I cannot really justify buying one, and making it blindly wouldn't really be enjoyable. I'll maybe ask around if Elgato would be willing to send me one. The plugin is open-source, so alternatively someone else with the new model can add the support.

**Comment by jonjonsson** [comment]
That is understandable. I dropped a note in the Stream Deck + Q&A Reddit thread that they should support you :) We can hope. Thanks!

**Comment by CZDanol** [comment]
Good news! I've been able to get hands on a unit, so I'll be adding the SD+ support, hopefully this month.

**Comment by jonjonsson** [comment]
Hell yeah! Looking forward to it.

**Comment by CZDanol** [comment]
Done, testing version available on https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2 under the releases section.

**Comment by jonjonsson** [comment]
Works beautifully! My most used plugin for sure.
