### ISSUE TITLE
Error 005 Network Error

### ISSUE THREAD

**Issue by photojoe** [CZDanol/streamdeck-discordmixer#14]
recived this error recently and unable to diagnose a solution tried re-installing, running in admin, re linking discord ect. everythiing else on stream deck/pc working fine. unable to use dvm at all

**Comment by CZDanol** [comment]
This is an old repository - I'm now using https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2.

Also, please come to our discord server for this: https://discord.com/invite/294BQE6Xdp
