### ISSUE TITLE
Implement ability to change volume up and down steps?

### ISSUE THREAD

**Issue by N8teAnderson** [CZDanol/streamdeck-discordmixer#8]

**Comment by N8teAnderson** [comment]
I love this plugin, it has already captivated me and I've had it for about 10 minutes, one tiny thing I wish was a feature was the ability to customize how much the audio increases or decreases per person. If this is an easy addition I would ask you please quickly add just for a quality of life update, and if it isn't easy to add no big deal because this plugin is already extremely helpful and I am so grateful that you have put the time into making it.

Thank you!

**Comment by CZDanol** [comment]
Hello, finished in the latest release (I've switched to a new repository: https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2)
